language: java

before_install:
  - chmod +x gradlew

before_deploy:
  - echo "Creating release tag if necessary"

deploy:
  - provider: script
    script: echo "Deploying to Artifactory"
    on:
      branch: master
      tags: false
  - provider: script
    script: echo "Deploying to Bintray"
    on:
      branch: master
      tags: true

after_deploy:
  - echo "Pushing tags"