jobs:
  include:
    - stage: pre_install
      script: chmod +x gradlew
    - stage: install
      script: ./gradlew assemble
    - stage: test
      script: ./gradlew check
    - stage: deploy
      script: ./gradlew tasks