language: java

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: printTasks
      script: ./gradlew tasks
    - stage: echoText
      script: echo "text"
    -
      script: echo "wow"