language: java

before_install:
  - chmod +x gradlew
  - chmod -R +x travis_scripts

## Default install
#install:
#  - ./gradlew assemble

## Default script
#script:
#  - ./gradlew check

before_deploy:
  - echo "Creating release tag if necessary"
  - ./travis_scripts/tag_if_release.sh
  - echo "git describe $(git describe)"

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - echo "Deploying to Artifactory"
      - chmod +x gradlew && ./gradlew artifactoryPublish
    on:
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script:
      - echo "Deploying to Bintray"
      - ./gradlew bintrayUpload
      - echo "Deploying to Gradle Plugin Portal"
      - ./gradlew publishPlugins
    on:
      branch: master
      tags: true

after_deploy:
  - echo "Pushing tags"
#  - ./travis_scripts/push_tag_if_release.sh
  - echo "Setting next snapshot"
#  - ./travis_scripts/set_next_snapshot.sh