language: java

before_install:
  - chmod +x gradlew

## Default install
#install:
#  - ./gradlew assemble

## Default script
#script:
#  - ./gradlew check

before_deploy:
  - echo "Creating release tag if necessary"

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "Deploying to Artifactory"
    on:
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script: echo "Deploying to Bintray"
    on:
      branch: master
      tags: true

after_deploy:
  - echo "Pushing tags"