language: java

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: install-test
    - stage: echoText
      install: ignore
      script: echo "text"
    -
      install: ignore
      script: echo "wow"